import type { VercelRequest, VercelResponse } from "@vercel/node";

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const hasGeminiKey = Boolean(process.env.GEMINI_API_KEY);

  // For now, return deterministic demo data so the UI populates.
  // Next step is swapping this to call Gemini and store results.
  return res.status(200).json({
    ok: true,
    hasGeminiKey,
    syncedAt: new Date().toISOString(),
    generated: {
      items: [
        {
          id: "item-1",
          childId: "child-1",
          type: "Prep",
          description: "Bring library book",
          dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
          status: "Open",
          source: "Demo Sync",
        },
        {
          id: "item-2",
          childId: "child-2",
          type: "Event",
          description: "Spirit Day",
          dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
          status: "Open",
          source: "Demo Sync",
        },
      ],
      briefing: {
        id: "briefing-2",
        createdAt: new Date().toISOString(),
        text: "Demo briefing generated by Sync Agent. Next step: real ingestion + Gemini summarization.",
      },
    },
  });
}